name: Cypress Tests

on: [push]

env:
  VITE_API_URL: http://localhost:3001
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies & Build
        uses: cypress-io/github-action@b80418579b5d0736b8d0f81c524800dc46a62942
        with:
          # just build and perform install
          build: npm run build
          runTests: false
      - name: CT Tests
        uses: cypress-io/github-action@b80418579b5d0736b8d0f81c524800dc46a62942 # use the explicit version number
        env:
        DEBUG: '@cypress/github-action'
        with:
          install: false
          component: true
          # command: npm run test:ct:ci:client-react
          record: true
          auto-cancel-after-failures: 2
          working-directory: ./client-react
          command-prefix: ' '
      - name: Start Client & Server
        run: npm run start:ci:react &
      - name: E2E Tests
        uses: cypress-io/github-action@b80418579b5d0736b8d0f81c524800dc46a62942 # use the explicit version number
        with:
          install: false
          command: npm run test:e2e:ci:client-react
          record: true
          wait-on: 'http://localhost:3000, http://localhost:3001/heroes'      
      - name: API Tests
        uses: cypress-io/github-action@b80418579b5d0736b8d0f81c524800dc46a62942 # use the explicit version number
        with:
          install: false
          command: npm run test:api:ci
          wait-on: 'http://localhost:3001/heroes'
